field.widget.settings.explore_courses_url:
  type: mapping
  label: 'ExploreCourses URL widget settings'
  mapping:
    api_version:
      type: string
      label: 'API version'
    placeholder_url:
      type: string
      label: 'Placeholder URL'
    placeholder_title:
      type: string
      label: 'Placeholder title'
