ports:
  - port: 3306
    onOpen: ignore
    visibility: private
  - port: 33060
    onOpen: ignore
    visibility: private
  - port: 8001
    onOpen: open-preview
    visibility: public
image: pookmish/drupal8ci:gitpod
tasks:
  - before: |
      mkdir -p ~/.ssh
      if [[ ! -z $SSH_PRIVATE_KEY ]]; then
          echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      fi
      if [[ ! -z $GITCONFIG ]]; then
          echo $GITCONFIG | base64 -d > ~/.gitconfig && chmod 644 ~/.gitconfig
      fi
    init: >
      export PACKAGE=`cat composer.json | jq -r '.name'` &&
      export PROFILE_NAME=`ls | grep info.yml | sed 's/\.info.*//'` &&
      export PROFILE_BRANCH=`git rev-parse --abbrev-ref HEAD` &&

      cd /workspace &&

      rm -rf $GITPOD_REPO_ROOT &&
      git clone --branch 2.x https://github.com/SU-SWS/acsf-cardinalsites-public.git $GITPOD_REPO_ROOT &&
      cd $GITPOD_REPO_ROOT &&

      composer require $PACKAGE:"dev-$PROFILE_BRANCH || $PROFILE_BRANCH-dev" --no-update &&
      composer update --no-interaction &&
      rm -rf docroot/*/custom/* &&
      composer install --prefer-source --no-interaction &&

      drush sws:multisite:settings &&
      sed -i "s|uri:.*|uri: $(gp url 8001)|" docroot/sites/default/local.drush.yml &&

      cp .gitpod/global.settings.php docroot/sites/settings/global.settings.php &&
      cp .gitpod/default.local.services.yml docroot/sites/local.services.yml &&

      drush site-install $PROFILE_NAME -v -y &&
      drush cset stage_file_proxy.settings origin 'localhost' -y &&

      cd $GITPOD_REPO_ROOT/docroot/profiles/custom/$PROFILE_NAME &&
      git remote set-url origin $(git remote get-url --push origin)
    command: |
      cd $GITPOD_REPO_ROOT &&
      apache2ctl restart &&
      git config core.fileMode false &&
      sed -i "s|uri:.*|uri: $(gp url 8001)|" docroot/sites/default/local.drush.yml &&
      drush uli &&
      drush uli | xargs gp preview --external
