<?php

/**
 * @file
 * stanford_profile.install
 */

/**
 * Implements hook_update_last_removed().
 */
function stanford_profile_update_last_removed() {
  return 9104;
}

/**
 * Remove data for paragraph rows.
 */
function stanford_profile_update_9105() {
  $tables = [
    'paragraph_row__su_page_components',
    'paragraph_row__su_pubs_components',
    'paragraph_row_revision__su_page_components',
    'paragraph_row_revision__su_pubs_components',
    'paragraph_rows_field_revision',
    'paragraph_rows_item',
    'paragraph_rows_item_field_data',
    'paragraph_rows_revision',
  ];
  foreach ($tables as $table) {
    \Drupal::database()->truncate($table)->execute();
  }
}

/**
 * Removes content from taxonomy terms.
 */
function stanford_profile_update_9106() {
  $vocabulary_names = [
    'opportunity_tag_filters',
    'opportunity_type',
    'opportunity_sponsor'
  ];

  foreach ($vocabulary_names as $vocabulary_name) {
    $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vocabulary_name, 0, NULL, TRUE);

    foreach ($terms as $term) {
      $term->delete();
    }
  }
}
