<?php

declare(strict_types=1);

/**
 * Implements hook_library_info_alter().
 */
function jemison_library_info_alter(&$libraries, $extension) {
  // Keep libraries that are part of this theme.
  if (\Drupal::service('theme_handler')->themeExists($extension)) {
    return;
  }
  // Exclude libraries that are part of Stanford modules.
  if (preg_match('/(stanford_|jumpstart|react|ui_pattern)/', $extension)) {
    $libraries = [];
  }
}
