minimally_branded_subtheme.settings:
  type: theme_settings
  label: 'Minimally Branded Subtheme settings'
  mapping:
    color_scheme_variant:
      type: string
      label: 'Color Scheme Variant'
    layout_variant:
      type: string
      label: 'Layout Variant'
    typography_variant:
      type: string
      label: 'Typography Variant'
    button_variant:
      type: string
      label: 'Button Variant'