name: "Stanford Profile Config Overrides"
description: Using config_pages module, override some config settings.
version: 8.x-1.0-dev
core_version_requirement: ^8 || ^9
type: module
project: Stanford
dependencies:
  - config_pages:config_pages
