<?php

/**
 * @file
 * Contains stanford_image_styles_preview.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function stanford_image_styles_preview_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the stanford_image_styles_preview module.
    case 'stanford_image_styles_preview.preview_form':
      $output = '<p>' . t('Provides a way to preview of all image styles after effects are applied.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_local_tasks_alter().
 */
function stanford_image_styles_preview_local_tasks_alter(&$local_tasks) {
  if (isset($local_tasks['entity.image_style.collection'])) {
    $local_tasks['entity.image_style.collection']['title'] = t('Image Styles');
  }
}
