<?php

/**
 * @file
 * stanford_profile_styles.module
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_page_attachments().
 */
function stanford_profile_styles_page_attachments(array &$attachments) {

  // Always attach to a page.
  $attachments['#attached']['library'][] = 'stanford_profile_styles/stanford_profile_styles';
  $attachments['#attached']['library'][] = 'stanford_profile_styles/wysiwyg';

  // Get the node from the route.
  $node = \Drupal::routeMatch()->getParameter('node');

  // Not a node.. Then just continue.
  if (!$node) {
    return;
  }

  // Check for our type and add library if a match.
  if ($node->getType() == "stanford_page") {
    $attachments['#attached']['library'][] = 'stanford_profile_styles/stanford_page';
  }

}

/**
 * Implements hook_preprocess_HOOK().
 */
function stanford_profile_styles_preprocess_react_paragraphs(&$variables) {
  foreach ($variables['rows'] as &$row) {
    foreach ($row['items'] as &$item) {
      // Add some classes to the react items for our css.
      $bundle = $item['entity']['#paragraph']->bundle();
      $item['attributes']['class'][] = Html::cleanCssIdentifier("ptype-$bundle");
      $item['attributes']['class'][] = 'paragraph-item';
    }
  }
}
