<?php

/**
 * @file
 * stanford_profile_styles.module
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\editor\Entity\Editor;

/**
 * Implements hook_page_attachments().
 */
function stanford_profile_styles_page_attachments(array &$attachments) {

  // Always attach to a page.
  $attachments['#attached']['library'][] = 'stanford_profile_styles/stanford_profile_styles';

  // Attach admin styles to admin pages.
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  if ($is_admin) {
    $attachments['#attached']['library'][] = 'stanford_profile_styles/admin';
  }

  // Get the node from the route.
  $node = \Drupal::routeMatch()->getParameter('node');

  // Not a node.. Then just continue.
  if (!$node) {
    return;
  }

  // Check for our type and add library if a match.
  if ($node->getType() == "stanford_page") {
    $attachments['#attached']['library'][] = 'stanford_profile_styles/stanford_page';
  }

}

/**
 * Implements hook_field_widget_multivalue_WIDGET_TYPE_form_alter().
 */
function stanford_profile_styles_field_widget_multivalue_paragraphs_form_alter(array &$elements, FormStateInterface $form_state, array $context) {
  $elements['#attached']['library'][] = 'stanford_profile_styles/field_widgets';;
}

/**
 * Implements hook_preprocess_entity().
 */
function stanford_profile_styles_preprocess_paragraph(&$vars) {
  $type = $vars['paragraph']->bundle();
  if ($type == "stanford_wysiwyg") {
    $vars['#attached']['library'][] = "stanford_profile_styles/stanford_paragraph_wysiwyg";
  }
}

/**
 * Implements hook_ckeditor_css_alter().
 */
function stanford_profile_styles_ckeditor_css_alter(array &$css, Editor $editor) {
  if (!$editor->hasAssociatedFilterFormat()) {
    return;
  }

  $known_formats = [
    'stanford_html',
    'stanford_minimal_html',
  ];

  if (in_array($editor->getFilterFormat()->id(), $known_formats)) {
    $css[] = drupal_get_path('module', 'stanford_profile_styles') . '/dist/css/stanford_profile_styles.ckeditor.css';
  }
}
