stanford_basic.settings:
  type: theme_settings
  label: 'Stanford Basic theme settings'
  mapping:
    browser_sync:
      type: mapping
      label: 'Enable Browser Sync'
      mapping:
        enabled:
          type: boolean
          label: 'Enable Browser Sync'
        host:
          type: string
          label: 'Host'
        port:
          type: integer
          label: 'Port'
    clear_registry:
      type: boolean
      label: 'Enable clear Registry'
    lockup:
      options:
        type: string
        label: 'Lockup Options'
      line1:
        type: text
        label: 'Line 1'
      line2:
        type: text
        label: 'Line 2'
      line3:
        type: text
        label: 'Line 3'
      line4:
        type: text
        label: 'Line 4'
      line5:
        type: text
        label: 'Line 5'
