<?php

/**
 * @file
 * Stanford_courses_importer.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Cache\Cache;
/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter the config form to add the migrate_tools UI.
 */
function stanford_courses_importer_form_config_pages_stanford_courses_importer_form_alter(array &$form, FormStateInterface $form_state) {
  $form['actions']['#type'] = 'fieldset';

  $form['actions']['import'] = [
    '#type' => 'submit',
    '#value' => t('Save & Import'),
    '#name' => 'op',
    '#button_type' => 'primary',
    '#submit' => [
      '::submitForm',
      '::save',
      'stanford_courses_importer_form_config_pages_stanford_courses_importer_form_alter_submit',
    ],
  ];
  return $form;
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function stanford_courses_importer_config_pages_presave(EntityInterface $entity) {
  // Clear out config and migration cache to allow config overrides to take
  // effect.
  if ($entity->bundle() == 'stanford_courses_importer') {
    Cache::invalidateTags([
      'config:migrate_plus.migration.stanford_courses_importer',
      'migration_plugins',
    ]);
  }
}

/**
 * Submit handler for the config form override.
 *
 * @param array $form
 *   The form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function stanford_courses_importer_form_config_pages_stanford_courses_importer_form_alter_submit(array &$form, FormStateInterface $form_state) {
  $migration_service = \Drupal::service('stanford_migrate')
    ->setBatchExecution(TRUE);
  $migration_service->executeMigrationId('stanford_courses');
}
