name: PHPUnit and Acceptance Tests
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  phpunit:
    name: PHPUnit Coverage Tests
    runs-on: ubuntu-latest
    container:
      image: pookmish/drupal8ci:php8.3
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: drupal
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
          MYSQL_ROOT_PASSWORD: drupal
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
        with:
          path: project
      - name: Build project
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        run: |
          mysql -h mysql -P 3306 -u root -pdrupal -e 'SET GLOBAL max_allowed_packet=67108864;' &&
          composer global require su-sws/stanford-caravan:11.x-dev &&
          ~/.config/composer/vendor/bin/sws-caravan phpunit /var/www/html --extension-dir=$GITHUB_WORKSPACE/project --with-coverage
      - name: Save Test Results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: d11-unit-tests-results
          path: /var/www/html/artifacts
  codeception:
    name: Codeception
    strategy:
      fail-fast: false
      matrix:
        suite: [ acceptance, functional ]
        piece: [ 1 ]
    runs-on: ubuntu-latest
    env:
      DRUPAL_DATABASE_NAME: drupal
      DRUPAL_DATABASE_USERNAME: drupal
      DRUPAL_DATABASE_PASSWORD: drupal
      DRUPAL_DATABASE_HOST: mysql
    container:
      image: pookmish/drupal8ci:php8.3
      options: '--network-alias drupal8ci'
    services:
      selenium:
        image: selenium/standalone-chrome:130.0
        options: '--shm-size="2g"'
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: drupal
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
          MYSQL_ROOT_PASSWORD: drupal
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
        with:
          path: project
      - name: Run tests
        env:
          STANFORD_ENCRYPT: ${{ secrets.STANFORD_ENCRYPT }}
        run: |
          mysql -h mysql -P 3306 -u root -pdrupal -e 'SET GLOBAL max_allowed_packet=67108864;' &&
          composer global require su-sws/stanford-caravan:11.x-dev &&
          ~/.config/composer/vendor/bin/sws-caravan codeception /var/www/html --extension-dir=$GITHUB_WORKSPACE/project --suites=${{ matrix.suite }} &&
          if [ ! -f /var/www/html/artifacts/acceptance/results.html ]; then
              exit 1
          fi
      - name: Save Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: d11-acceptance-tests-results
          path: /var/www/html/artifacts
