name: Tests
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    container:
      image: pookmish/drupal8ci:php8.3
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: drupal
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
          MYSQL_ROOT_PASSWORD: drupal
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
        with:
          path: project
      - name: Build project
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        run: |
          mysql -h mysql -P 3306 -u root -pdrupal -e 'SET GLOBAL max_allowed_packet=67108864;' &&
          composer global require su-sws/stanford-caravan:dev-support-drupal-versions &&
          ~/.config/composer/vendor/bin/sws-caravan phpunit /var/www/html --extension-dir=$GITHUB_WORKSPACE/project --with-coverage
      - name: Save Test Results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: d11-unit-tests-results
          path: /var/www/html/artifacts
  shard_matrix:
    name: Test Shards
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate Shard Matrix
        id: set-matrix
        run: |
          n=${{ vars.TEST_SHARDS || 4 }} &&
          numbers=($(seq 1 $n)) &&
          json=$(printf '%s\n' "${numbers[@]}" | jq -R . | jq -s -c .) &&
          echo "Test shards: $json" &&
          echo "matrix=$json" >> $GITHUB_OUTPUT
  codeception:
    name: Codeception
    needs: [shard_matrix]
    strategy:
      fail-fast: false
      matrix:
        suite: [ acceptance, functional ]
        shard: ${{fromJSON(needs.shard_matrix.outputs.matrix)}}
    runs-on: ubuntu-latest
    env:
      DRUPAL_DATABASE_NAME: drupal
      DRUPAL_DATABASE_USERNAME: drupal
      DRUPAL_DATABASE_PASSWORD: drupal
      DRUPAL_DATABASE_HOST: mysql
    container:
      image: pookmish/drupal8ci:php8.3
      options: '--network-alias drupal8ci'
    services:
      selenium:
        image: selenium/standalone-chrome:130.0
        options: '--shm-size="2g"'
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: drupal
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
          MYSQL_ROOT_PASSWORD: drupal
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
        with:
          path: project
      - name: Run tests
        env:
          STANFORD_ENCRYPT: ${{ secrets.STANFORD_ENCRYPT }}
        run: |
          n=${{ vars.TEST_SHARDS || 4 }} &&
          mysql -h mysql -P 3306 -u root -pdrupal -e 'SET GLOBAL max_allowed_packet=67108864;' &&
          composer global require su-sws/stanford-caravan:dev-support-drupal-versions &&
          ~/.config/composer/vendor/bin/sws-caravan codeception /var/www/html --extension-dir=$GITHUB_WORKSPACE/project --suites=${{ matrix.suite }} --shard=${{ matrix.shard }}/$n &&
          if [ ! -f /var/www/html/artifacts/${{ matrix.suite }}/results.html ]; then
              exit 1
          fi
      - name: Save Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: codeception-${{ matrix.suite }}-${{ matrix.shard }}
          path: /var/www/html/artifacts
  all-tests-pass:
    # This job will be skipped if the requirements pass. If any of the dependent
    # jobs fail, this will run and throw an error, causing the PR to fail.
    name: All Tests Pass
    if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
    needs: [phpunit, codeception]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Some workflows have failed!"
          exit 1

